export const GET_LOGIN_DATA = "GET_LOGIN_DATA";
export const SET_LOGIN_DATA = "SET_LOGIN_DATA";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_LOGIN_PAGE_TEXT_ERROR = "SET_LOGIN_PAGE_TEXT_ERROR";
export const GET_LOGIN_PAGE_TEXT_DATA = "GET_LOGIN_PAGE_TEXT_DATA";
export const SET_LOGIN_PAGE_TEXT_DATA = "SET_LOGIN_PAGE_TEXT_DATA";
