export const GET_CHECKOUT_PAGE_DATA = "GET_CHECKOUT_PAGE_DATA";
export const SET_CHECKOUT_PAGE_DATA = "SET_CHECKOUT_PAGE_DATA";
export const SET_CHECKOUT_PAGE_ERROR = "SET_ERROR_CHECKOUT_PAGE_DATA";
export const GET_CHECKOUT_PAGE_STEP_DATA = "GET_CHECKOUT_PAGE_STEP_DATA";
export const SET_CHECKOUT_PAGE_STEP_DATA = "SET_CHECKOUT_PAGE_STEP_DATA";
export const SET_CHECKOUT_PAGE_STEP_ERROR = "SET_CHECKOUT_PAGE_STEP_ERROR";
