export const ADD_PARAMETERS = "ADD_PARAMETERS";
export const SET_ERGEBNIS_PAGE_ERROR = "SET_ERGEBNIS_PAGE_ERROR";
export const GET_ERGEBNIS_PAGE_TEXT = "GET_ERGEBNIS_PAGE_TEXT";
export const SET_ERGEBNIS_PAGE_TEXT = "SET_ERGEBNIS_PAGE_TEXT";
