export const SET_HEADER_TEXT = "SET_HEADER_TEXT";
export const SET_HEADER_LANGUAGE = "SET_HEADER_LANGUAGE";
export const SET_HEADER_CONTACT = "SET_HEADER_CONTACT";
export const SET_HEADER_PAGE_TEXT = "SET_HEADER_PAGE_TEXT";
export const GET_HEADER = "GET_HEADER";
export const SET_HEADER_ERROR = "SET_HEADER_ERROR";
