export const GET_NAVBAR_SETTINGS = "GET_NAVBAR_SETTINGS";
export const SET_NAVBAR_SETTINGS = "SET_NAVBAR_SETTONGS";
export const SET_ERROR = "SET_ERROR";
export const GET_HOMEPAGE_SECTIONONE = "GET_HOMEPAGE_SECTIONONE";
export const SET_HOMEPAGE_SECTIONONE = "SET_HOMEPAGE_SECTIONONE";
export const GET_HEADER_CONTACTS = "GET_HEADER_CONTACTS";
export const SET_HEADER_CONTACTS = "SET_HEADER_CONTACTS";
export const GET_HOMEPAGE_PRODWLTXT_ONE = "GET_HOMEPAGE_PRODWLTXT_ONE";
export const SET_HOMEPAGE_HEADERTXTS = 'SET_HOMEPAGE_HEADERTXTS';
export const GET_COLLECTION_SHOPS = 'GET_COLLECTION_SHOPS';
export const SET_COLLECTION_SHOPS = 'SET_COLLECTION_SHOPS';
export const GET_INSPIRATIONS = 'GET_INSPIRATIONS';
export const SET_INSPIRATIONS = 'SET_INSPIRATIONS';
export const SET_LOADED = "SET_LOADED";
export const SET_FOUR_ICONS = "SET_FOUR_ICONS"
export const SET_MIDFOOT = "SET_MIDFOOT";
export const SET_NEWSLETTER_TEXT = "SET_NEWSLETTER_TEXT";




export const GET_RENDER_MODAL="GET_RENDER_MODAL"
export const HOMEPAGE_LOADER="HOMEPAGE_LOADER"