export const GET_KONTO_MAIN_BOXES_DATA = "GET_KONTO_MAIN_BOXES_DATA";
export const SET_KONTO_MAIN_BOXES_DATA = "SET_KONTO_MAIN_BOXES_DATA";
export const GET_KONTO_MAIN_BOXES_ERROR = "GET_KONTO_MAIN_BOXES_ERROR";
export const GET_KONTO_PAGE_TEXT_DATA = "GET_KONTO_PAGE_TEXT_DATA";
export const SET_KONTO_PAGE_TEXT_DATA = "SET_KONTO_PAGE_TEXT_DATA";
export const GET_KONTO_PAGE_TEXT_ERROR = "GET_KONTO_PAGE_TEXT_ERROR";
