export const SET_RENDER_MODAL_ERROR = "SET_RENDER_MODAL_ERROR";
export const GET_RENDER_MODAL_DATA = "GET_RENDER_MODAL_DATA";
export const SET_RENDER_MODAL_DATA = "SET_RENDER_MODAL_DATA";
export const SET_FIRST_INTRO_ERROR = "SET_FIRST_INTRO_ERROR";
export const GET_FIRST_INTRO_DATA = "GET_FIRST_INTRO_DATA";
export const SET_FIRST_INTRO_DATA = "SET_FIRST_INTRO_DATA";
export const SET_PRODUCTS_WITH_LEFT_TEXT_ONE_ERROR =
  "SET_PRODUCTS_WITH_LEFT_TEXT_ONE_ERROR";
export const GET_PRODUCTS_WITH_LEFT_TEXT_ONE_DATA =
  "GET_PRODUCTS_WITH_LEFT_TEXT_ONE_DATA";
export const SET_PRODUCTS_WITH_LEFT_TEXT_ONE_DATA =
  "SET_PRODUCTS_WITH_LEFT_TEXT_ONE_DATA";
export const SET_PRODUCTS_WITH_LEFT_TEXT_TWO_ERROR =
  "SET_PRODUCTS_WITH_LEFT_TEXT_TWO_ERROR";
export const GET_PRODUCTS_WITH_LEFT_TEXT_TWO_DATA =
  "GET_PRODUCTS_WITH_LEFT_TEXT_TWO_DATA";
export const SET_PRODUCTS_WITH_LEFT_TEXT_TWO_DATA =
  "SET_PRODUCTS_WITH_LEFT_TEXT_TWO_DATA";
export const SET_SECTION_TEXT_ERROR = "SET_SECTION_TEXT_ERROR";
export const GET_SECTION_TEXT_DATA = "GET_SECTION_TEXT_DATA";
export const SET_SECTION_TEXT_DATA = "SET_SECTION_TEXT_DATA";
export const SET_INSPIRATION_ONE_TEXT_ERROR = "SET_INSPIRATION_ONE_TEXT_ERROR";
export const GET_INSPIRATION_ONE_TEXT_DATA = "GET_INSPIRATION_ONE_TEXT_DATA";
export const SET_INSPIRATION_ONE_TEXT_DATA = "SET_INSPIRATION_ONE_TEXT_DATA";
export const SET_INSPIRATION_TWO_TEXT_ERROR = "SET_INSPIRATION_TWO_TEXT_ERROR";
export const GET_INSPIRATION_TWO_TEXT_DATA = "GET_INSPIRATION_TWO_TEXT_DATA";
export const SET_INSPIRATION_TWO_TEXT_DATA = "SET_INSPIRATION_TWO_TEXT_DATA";
export const SET_INSPIRATION_THREE_TEXT_ERROR = "SET_INSPIRATION_THREE_TEXT_ERROR";
export const GET_INSPIRATION_THREE_TEXT_DATA = "GET_INSPIRATION_THREE_TEXT_DATA";
export const SET_INSPIRATION_THREE_TEXT_DATA = "SET_INSPIRATION_THREE_TEXT_DATA";
export const SET_NEWS_SECTION_TEXT_ERROR = "SET_NEWS_SECTION_TEXT_ERROR";
export const GET_NEWS_SECTION_TEXT_DATA = "GET_NEWS_SECTION_TEXT_DATA";
export const SET_NEWS_SECTION_TEXT_DATA = "SET_NEWS_SECTION_TEXT_DATA";
export const SET_DPAB_MAGAZINE_TEXT_ERROR = "SET_DPAB_MAGAZINE_TEXT_ERROR";
export const GET_DPAB_MAGAZINE_TEXT_DATA = "GET_DPAB_MAGAZINE_TEXT_DATA";
export const SET_DPAB_MAGAZINE_TEXT_DATA = "SET_DPAB_MAGAZINE_TEXT_DATA";
export const SET_DPAB_BOTTOM_TEXT_ERROR = "SET_DPAB_BOTTOM_TEXT_ERROR";
export const GET_DPAB_BOTTOM_TEXT_DATA = "GET_DPAB_BOTTOM_TEXT_DATA";
export const SET_DPAB_BOTTOM_TEXT_DATA = "SET_DPAB_BOTTOM_TEXT_DATA";
