export const SET_LEXIKON_PAGE_TEXT_ERROR = "SET_LEXIKON_PAGE_TEXT_ERROR";
export const GET_LEXIKON_PAGE_TEXT_DATA = "GET_LEXIKON_PAGE_TEXT_DATA";
export const SET_LEXIKON_PAGE_TEXT_DATA = "SET_LEXIKON_PAGE_TEXT_DATA";
export const SET_LEXIKON_THEME_ERROR = "SET_LEXIKON_THEME_ERROR";
export const GET_LEXIKON_THEME_DATA = "GET_LEXIKON_THEME_DATA";
export const SET_LEXIKON_THEME_DATA = "SET_LEXIKON_THEME_DATA";