export const SET_MAGAZINE_ONE_PAGE_TEXT_ERROR =
  "SET_MAGAZINE_ONE_PAGE_TEXT_ERROR";
export const GET_MAGAZINE_ONE_PAGE_TEXT_DATA =
  "GET_MAGAZINE_ONE_PAGE_TEXT_DATA";
export const SET_MAGAZINE_ONE_PAGE_TEXT_DATA =
  "SET_MAGAZINE_ONE_PAGE_TEXT_DATA";
