export const SET_MAGAZINE_PAGE_TEXT_ERROR = "SET_MAGAZINE_PAGE_TEXT_ERROR";
export const GET_MAGAZINE_PAGE_TEXT_DATA = "GET_MAGAZINE_PAGE_TEXT_DATA";
export const SET_MAGAZINE_PAGE_TEXT_DATA = "SET_MAGAZINE_PAGE_TEXT_DATA";
export const SET_MAGAZINE_CATEGORIES_ERROR = "SET_MAGAZINE_CATEGORIES_ERROR";
export const SET_MAGAZINE_CATEGORIES_DATA = "SET_MAGAZINE_CATEGORIES_DATA";
export const GET_MAGAZINE_CATEGORIES_DATA = "GET_MAGAZINE_CATEGORIES_DATA";
export const SET_MAGAZINE_CATEGORY_INDEX = "SET_MAGAZINE_CATEGORY_INDEX";
export const SET_MAGAZINE_ARTICLES_ERROR = "SET_MAGAZINE_ARTICLES_ERROR";
export const SET_MAGAZINE_ARTICLES_DATA = "SET_MAGAZINE_ARTICLES_DATA";
export const GET_MAGAZINE_ARTICLES_DATA = "GET_MAGAZINE_ARTICLES_DATA";
export const SET_MAGAZINE_BLOGS_ERROR = "SET_MAGAZINE_BLOGS_ERROR";
export const SET_MAGAZINE_BLOGS_DATA = "SET_MAGAZINE_BLOGS_DATA";
export const GET_MAGAZINE_BLOGS_DATA = "GET_MAGAZINE_BLOGS_DATA";
export const GET_MAGAZINE_SINGLE_ARTICLE_DATA =
  "GET_MAGAZINE_SINGLE_ARTICLE_DATA";
export const SET_MAGAZINE_SINGLE_ARTICLE_ERROR =
  "SET_MAGAZINE_SINGLE_ARTICLE_ERROR";
export const SET_MAGAZINE_SINGLE_ARTICLE_DATA =
  "SET_MAGAZINE_SINGLE_ARTICLE_DATA";
export const GET_MAGAZINE_SINGLE_BLOG_DATA = "GET_MAGAZINE_SINGLE_BLOG_DATA";
export const SET_MAGAZINE_SINGLE_BLOG_ERROR = "SET_MAGAZINE_SINGLE_BLOG_ERROR";
export const SET_MAGAZINE_SINGLE_BLOG_DATA = "SET_MAGAZINE_SINGLE_BLOG_DATA";
