export const GET_MARKENS = "GET_MARKENS"
export const SET_MARKENS = "SET_MARKENS"
export const GET_MARKEN_DATA = "GET_MARKEN_DATA"
export const SET_MARKEN_DATA = "SET_MARKEN_DATA"
export const SET_ERROR = "SET_ERROR"