export const GET_RECOMMENDATION_PAGE_TEXT = "GET_RECOMMENDATION_PAGE_TEXT";
export const SET_RECOMMENDATION_PAGE_TEXT = "SET_RECOMMENDATION_PAGE_TEXT";
export const SET_RECOMMENDATION_ERROR = "SET_RECOMMENDATION_ERROR";
