export const GET_SEARCH_PAGE_TEXT_DATA = "GET_SEARCH_PAGE_TEXT_DATA";
export const SET_SEARCH_PAGE_TEXT_DATA = "SET_SEARCH_PAGE_TEXT_DATA";
export const SET_SEARCH_PAGE_TEXT_ERROR = "SET_SEARCH_PAGE_TEXT_ERROR";
export const GET_SEARCH_DATA = "GET_SEARCH_DATA";
export const SET_SEARCH_DATA = "SET_SEARCH_DATA";
export const SET_SEARCH_ERROR = "SET_SEARCH_ERROR";
