export const GET_SINGLEPRODUCT_STYLE_TEXT = "GET_SINGLEPRODUCT_STYLE_TEXT";
export const SET_ERROR = "SET_ERROR";
export const SET_DATA_LOADED = "SET_DATA_LOADED";
export const GET_SINGLEPRODUCT_VARIANT_ID = "GET_SINGLEPRODUCT_VARIANT_ID";
